"""schema inicial

Revision ID: 0b1cf5038f57
Revises: 
Create Date: 2026-07-18 04:17:48.244827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1cf5038f57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'operador')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('watchdog_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_successful_cycle_at', sa.DateTime(), nullable=True),
    sa.Column('alert_active', sa.Boolean(), nullable=False),
    sa.Column('alert_sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username_attempted', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.CheckConstraint("result IN ('success', 'failure')", name='ck_audit_log_result'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('collection_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_em_falha_tst', sa.Integer(), nullable=True),
    sa.Column('total_sem_comunicacao', sa.Integer(), nullable=True),
    sa.Column('total_falso_positivo', sa.Integer(), nullable=True),
    sa.CheckConstraint("source IN ('scheduled', 'manual', 'watchdog')", name='ck_cycles_source'),
    sa.CheckConstraint("status IN ('running', 'success', 'error')", name='ck_cycles_status'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_cycles_started_at'), ['started_at'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('alerts_sent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('message_type', sa.String(length=24), nullable=False),
    sa.Column('accounts_added', sa.JSON(), nullable=True),
    sa.Column('accounts_removed', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('telegram_message_id', sa.String(length=64), nullable=True),
    sa.CheckConstraint("message_type IN ('entrada', 'saida', 'normalizacao', 'watchdog', 'watchdog_recovery')", name='ck_alerts_sent_message_type'),
    sa.ForeignKeyConstraint(['cycle_id'], ['collection_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts_sent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_sent_cycle_id'), ['cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_sent_sent_at'), ['sent_at'], unique=False)

    op.create_table('cycle_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=32), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('tst_failure_since', sa.DateTime(), nullable=True),
    sa.Column('last_event_code', sa.String(length=16), nullable=True),
    sa.Column('last_event_at', sa.DateTime(), nullable=True),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.CheckConstraint("classification IN ('sem_comunicacao', 'falso_positivo')", name='ck_cycle_accounts_classification'),
    sa.ForeignKeyConstraint(['cycle_id'], ['collection_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycle_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_accounts_account_number'), ['account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_cycle_accounts_cycle_id'), ['cycle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_accounts_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_cycle_accounts_account_number'))

    op.drop_table('cycle_accounts')
    with op.batch_alter_table('alerts_sent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_sent_sent_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_sent_cycle_id'))

    op.drop_table('alerts_sent')
    op.drop_table('settings')
    with op.batch_alter_table('collection_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_cycles_started_at'))

    op.drop_table('collection_cycles')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    op.drop_table('watchdog_state')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
