"""report_runs (relatorios atendimentos/disparos)

Revision ID: 1a41ee954233
Revises: 7c41d2a90b3e
Create Date: 2026-07-21 14:55:20.783743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a41ee954233'
down_revision = '7c41d2a90b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=16), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('extra_counts', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.CheckConstraint("module IN ('atendimentos', 'disparos')", name='ck_report_runs_module'),
    sa.CheckConstraint("status IN ('running', 'success', 'error')", name='ck_report_runs_status'),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_runs_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_runs_module'), ['module'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_runs_module'))
        batch_op.drop_index(batch_op.f('ix_report_runs_generated_at'))

    op.drop_table('report_runs')
    # ### end Alembic commands ###
