"""auvo_depara e auvo_chamados (modulo Chamados Auvo)

Revision ID: b95c01c8708b
Revises: 1a41ee954233
Create Date: 2026-07-23 17:45:27.760454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b95c01c8708b'
down_revision = '1a41ee954233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auvo_chamados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('gatilho', sa.String(length=24), nullable=False),
    sa.Column('conta_power', sa.String(length=32), nullable=True),
    sa.Column('cliente', sa.String(length=200), nullable=True),
    sa.Column('resultado', sa.String(length=16), nullable=False),
    sa.Column('id_tarefa_auvo', sa.String(length=64), nullable=True),
    sa.Column('origem_user_id', sa.Integer(), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.CheckConstraint("gatilho IN ('sem_comunicacao', 'disparos', 'teste')", name='ck_auvo_chamados_gatilho'),
    sa.CheckConstraint("resultado IN ('aberta', 'simulada', 'falha', 'repetida', 'sem_depara')", name='ck_auvo_chamados_resultado'),
    sa.ForeignKeyConstraint(['origem_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auvo_chamados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auvo_chamados_conta_power'), ['conta_power'], unique=False)
        batch_op.create_index(batch_op.f('ix_auvo_chamados_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_auvo_chamados_gatilho'), ['gatilho'], unique=False)
        batch_op.create_index(batch_op.f('ix_auvo_chamados_resultado'), ['resultado'], unique=False)

    op.create_table('auvo_depara',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_power', sa.String(length=32), nullable=False),
    sa.Column('nome_power', sa.String(length=200), nullable=False),
    sa.Column('id_auvo', sa.Integer(), nullable=True),
    sa.Column('nome_auvo', sa.String(length=200), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('OK', 'REVISAR', 'NAO')", name='ck_auvo_depara_status'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auvo_depara', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auvo_depara_conta_power'), ['conta_power'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auvo_depara', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auvo_depara_conta_power'))

    op.drop_table('auvo_depara')
    with op.batch_alter_table('auvo_chamados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auvo_chamados_resultado'))
        batch_op.drop_index(batch_op.f('ix_auvo_chamados_gatilho'))
        batch_op.drop_index(batch_op.f('ix_auvo_chamados_criado_em'))
        batch_op.drop_index(batch_op.f('ix_auvo_chamados_conta_power'))

    op.drop_table('auvo_chamados')
    # ### end Alembic commands ###
