"""tarefas pessoais (fixa/semana/dia)

Revision ID: ecae4d947f47
Revises: d90d1780e01f
Create Date: 2026-08-12 16:09:46.033571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecae4d947f47'
down_revision = 'd90d1780e01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('horizonte', sa.String(length=16), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('prioridade', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.CheckConstraint("horizonte IN ('fixa', 'semana', 'dia')", name='ck_tarefas_horizonte'),
    sa.CheckConstraint("prioridade IN ('baixa', 'media', 'alta')", name='ck_tarefas_prioridade'),
    sa.CheckConstraint("status IN ('pendente', 'feito')", name='ck_tarefas_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarefas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarefas_horizonte'), ['horizonte'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarefas_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarefas_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarefas_user_id'))
        batch_op.drop_index(batch_op.f('ix_tarefas_status'))
        batch_op.drop_index(batch_op.f('ix_tarefas_horizonte'))

    op.drop_table('tarefas')
    # ### end Alembic commands ###
