"""auvo_depara: supressao temporaria de conta

Revision ID: f48ebb3d3cf7
Revises: b95c01c8708b
Create Date: 2026-07-24 12:55:16.063025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48ebb3d3cf7'
down_revision = 'b95c01c8708b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auvo_depara', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('suprimido', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('suprimido_ate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('suprimido_motivo', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auvo_depara', schema=None) as batch_op:
        batch_op.drop_column('suprimido_motivo')
        batch_op.drop_column('suprimido_ate')
        batch_op.drop_column('suprimido')

    # ### end Alembic commands ###
